# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  delete:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish DINTEIOT/DINTEIOT.csproj -c Release -o website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: website
        # A file, directory or wildcard pattern that describes what to upload
        path: website/
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error  # <-- last line of build job: insert below this line
  
  web_deploy:
      needs: [build]
      name:  Deploy
      
      env: 
          WHO_TO_TRUST: ${{ secrets.DH_PASS }}
          run: echo "Đây là password :" env.WHO_TO_TRUST
      runs-on: ubuntu-latest
      steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: website
          path: website/
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: win5115.site4now.net
          username: hoangnh34-001
          password: ${{ secrets.DH_PASS }}
